### ISSUE TITLE
App no longer logs into SB

### ISSUE THREAD

**Issue by nbgibson** [LeslieAerts/saltydroid-issue-tracker#10]
I'm sure this is the least of your concerns since the app is no longer on the store, but it no longer allows users to log into their accounts on SaltyBet. Any chance of a resolution or is that something we'll have to wait for with the reupload?

**Comment by LeslieAerts** [comment]
Hey WarriusBird.

I recently tried logging in (Albeit in my most recent test version) And logging in still works. I'm not sure if it's the current release that was on the Play store that had that issue, but it's gone now :)

I'm still trying to get in touch with all parties for getting permission, but so far Salty, Twitch and Google like to wait at least 3 weeks before writing me a reply that doesn't really answer any questions.

I'm starting to finish up a new working version which I'll release as an signed APK so it will upgrade existing versions as well. I'm working on clearing out the Play store integration (donations and such). After that, we'll see how it goes.
