### ISSUE TITLE
Where is Saltydroid?

### ISSUE THREAD

**Issue by seagull** [LeslieAerts/saltydroid-issue-tracker#9]
I've been trying to find it, but it's been pulled from Google Play.
There's a few APK downloads but I don't trust them.
Were you planning on making it available again soon?

**Comment by LeslieAerts** [comment]
It has been pulled from the play store because of copyright issues. I'm working on getting it back, but it's a slow and painful process.

**Comment by seagull** [comment]
That's a bitch. Is there any chance you could stick an APK up in the meantime? I don't mind donating a few bucks for the paid version.

**Comment by LeslieAerts** [comment]
I'm working on possible alternatives. I'll probably finish up coding the latest version and put it on a G+ community or whatever.

**Comment by nbgibson** [comment]
Any updates boss?

**Comment by LeslieAerts** [comment]
See new beta release: https://plus.google.com/+LeslieAerts/posts/RHvgvaSfYxv
